# About/Contact
# -------------
author: Abdullah Barrak
email: a@abarrak.com
accounts:
  github: https://github.com/abarrak
  linkedin : https://linkedin.com/in/abarrak
  goodreads: https://goodreads.com/abarrak
  no_twitter: https://twitter.com/abarrak_
  

# Site Settings
# -------------
baseurl: ""
url: http://www.abarrak.com
title: Abdullah Barrak
subtitle: Abdullah Barrak's Blog
description: A passionate blog about computer programming, reading, thinking, and the like.
keywords: Software engineering, Web development, Computers, Programming, Reading
 

# Build Settings
# --------------
destination: '../abarrak.github.io'
Keep_files: ['.git', '.gitignore']
exclude: ['gulpfile.js', 'node_modules', 'package.json', 'Gemfile', 'Gemfile.lock', 'README.md']
markdown: kramdown
permalink: /:year/:month/:day/:title/
# lsi: true   # when have fair content !
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
paginate_path: /:num/
extlinks:
  attributes: { rel: nofollow, target: _blank }
  rel_exclude: ['abarrak.com']


# Defaults
# --------
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /:year/:month/:day/:title
      layout: post
      author: Abdullah Barrak
      excerpt_separator: <!-- post-excerpt -->
      comments: true
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
