# About/Contact
# -------------
author: Abdullah Barrak
url:  www.abarrak.com
email: a@abarrak.com
accounts:
  github: https://github.com/abarrak
  goodreads: https://www.goodreads.com/abarrak
  linkedin : https://www.linkedin.com/in/abarrak
  twitter: https://twitter.com/abarrak_

# Site Settings
# -------------
baseurl: ""
url: http://abarrak.com
languages: ['en', 'ar']
language_default: 'en'

# Build Settings
# --------------
destination: '../abarrak.github.io'
Keep_files: ['.git', '.gitignore']
exclude: ['gulpfile.js', 'node_modules', 'package.json']
markdown: kramdown
permalink: /:year/:month/:day/:title/
# lsi: true   when have fair content !
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-multiple-languages
  - jekyll-sitemap
paginate: 5
paginate_path: /:num/
extlinks:
  attributes: { rel: nofollow, target: _blank }
  rel_exclude: ['abarrak.com']


# Defaults
# --------
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /:year/:month/:day/:title
      layout: post
      author: Abdullah
      excerpt_separator: <!-- post-excerpt -->
      comments: true
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
