# About/Contact
# -------------
author: Abdullah Barrak
email: abdullah@abarrak.com
accounts:
  github: https://github.com/abarrak
  linkedin : https://linkedin.com/in/abarrak
  goodreads: https://goodreads.com/abarrak
  stackoverflow: https://stackoverflow.com/users/2925286/abdullah-barrak
  twitter: https://twitter.com/abalhafi


# Site Settings
# -------------
baseurl: ""
url: https://www.abarrak.com
title: global.title
subtitle: global.subtitle
description: global.description
keywords: global.keywords


# Build Settings
# --------------
destination: '../abarrak.github.io'
Keep_files: ['.git', '.gitignore']
exclude: ['gulpfile.js', 'node_modules', 'package.json', 'Gemfile', 'Gemfile.lock', 'package-lock.json', 'publish']
markdown: kramdown
permalink: /:year/:month/:day/:title/
# when have fair content !
# lsi: true
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
paginate: 5
paginate_path: /:num/
extlinks:
  attributes: { rel: nofollow, target: _blank }
  rel_exclude: ['abarrak.com']

languages: ["en", "ar"]
exclude_from_localizations: ['public']
default_locale_in_subfolder: false

# Defaults
# --------
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /:year/:month/:day/:title
      layout: post
      author: Abdullah Barrak
      excerpt_separator: <!-- post-excerpt -->
      comments: true
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
