#!/bin/bash

## Publish Script.
# profile using jekyll serve .. once done, run it,
# author: abarrak (github.com/abarrak)

printf "\n..... [1/2] Updating Source Files .....\n"
printf ".......................................\n"
git add .
git commit -m "Source Auto Update at: `date`"
git push origin src

printf "\n..... [2/2] Updating Site Files .....\n"
printf ".....................................\n"
jekyll build
cd ../abarrak.github.io
git add .
git commit -m "Auto Update at: `date`"
git push origin master

echo "..... Done ! ....."
echo ".................."
